org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_version=1.0.9
maven_group=com.rique.sodiumfpscapfix
archives_base_name=sodiumfpscapfix

fabric_loader_version=0.18.4

minecraft_1201=1.20.1
minecraft_1211=1.21.1
minecraft_12111=1.21.11

neoforge_1211=21.1.221
neoforge_12111=21.11.40-beta

fps_cap_max=1000000
