modLoader="javafml"
loaderVersion="[1,)"
license="Unlicense"

[[mixins]]
config="sodiumfpscapfix.mixins.json"

[[mods]]
modId="sodiumfpscapfix"
version="${version}"
displayName="Sodium FPS Cap Fix"
displayTest="IGNORE_ALL_VERSION"
logoFile="assets/sodiumfpscapfix/icon.png"
description='''Adds an FPS cap textbox and removes the 260 FPS ceiling.'''

[[dependencies.sodiumfpscapfix]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.sodiumfpscapfix]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"

[[dependencies.sodiumfpscapfix]]
modId="sodium"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="CLIENT"
